### ISSUE TITLE
Not able to install on redmine-4.0.0

### ISSUE THREAD

**Issue by rnitc** [ahamdan1990/redmine_time_log_pdf_export#1]
I tried to install this plugin on  Ubuntu 16.04.6 LTS with Redmine 4.0.0. when I extracted the files in the plugin folder entire redmine crashed. Could you please check or let me know the detailed steps for the same.

**Comment by ahamdan1990** [comment]
Make sure that you name the plugin "redmine_time_log_pdf_export" and not "redmine_time_log_pdf_export-main". In addition to the above can you please share your production log which you'll find it under the root installation of redmine/log/production.log

**Comment by ahamdan1990** [comment]
> I tried to install this plugin on Ubuntu 16.04.6 LTS with Redmine 4.0.0. when I extracted the files in the plugin folder entire redmine crashed. Could you please check or let me know the detailed steps for the same.

Make sure that you name the plugin "redmine_time_log_pdf_export" and not "redmine_time_log_pdf_export-main". In case that didn't work can you please share your production log which you'll find it under the root installation of redmine/log/production.log

**Comment by rnitc** [comment]
Hi Ahamdan,

I did the git clone in the plugins folder  and  "redmine_time_log_pdf_export" folder is created. I did try to see the production log unfortunately nothing is coming in the log. Yet the Redmine is not working after the git clone command.  hope I am missing something..

**Comment by rnitc** [comment]
Do i need to update or add any dependency file or gems to make it work...

**Comment by ahamdan1990** [comment]
> Do i need to update or add any dependency file or gems to make it work...

No it should work by just restarting your redmine instance I'm just adding a time log helper using the existing rbpdf gem and pdf library.
How are you running your redmine production using what ? 
Can you please start your redmine using this cmd just to check where it's giving error in which file:

bundle exec rails server webrick -e production

**Comment by ahamdan1990** [comment]
> Hi Ahamdan,
> 
> I did the git clone in the plugins folder and "redmine_time_log_pdf_export" folder is created. I did try to see the production log unfortunately nothing is coming in the log. Yet the Redmine is not working after the git clone command. hope I am missing something..

Regarding the log did you have the right permission to log folder?
Assuming you run Redmine with a user named "redmine":
     sudo chown -R redmine:redmine files log tmp public/plugin_assets
     sudo chmod -R 755 files log tmp public/plugin_assets
You have to run these cmd.
Try to reinstall the plugin now i made a bit change check if it's going to work

**Comment by rnitc** [comment]
> bundle exec rails server webrick -e production

here  is the log file after executing the above command 

redmine@vps:~/redmine-4.0.0$ bundle exec rails server webrick -e production
=> Booting WEBrick
=> Rails 5.2.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	72: from bin/rails:4:in `<main>'
	71: from bin/rails:4:in `require'
	70: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>'
	69: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
	68: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
	67: from /usr/share/rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	66: from /usr/share/rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	65: from /usr/share/rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	64: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform'
	63: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
	62: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	61: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:53:in `start'
	60: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:283:in `start'
	59: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
	58: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app'
	57: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
	56: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	55: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
	54: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
	53: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
	52: from config.ru:in `<main>'
	51: from config.ru:in `new'
	50: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
	49: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
	48: from config.ru:3:in `block in <main>'
	47: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	46: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	45: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	44: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	43: from /data/redmine/redmine-4.0.0/config/environment.rb:14:in `<top (required)>'
	42: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
	41: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
	40: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
	39: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
	38: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
	37: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
	36: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each'
	35: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
	34: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
	33: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `call'
	32: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	31: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
	30: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	29: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
	28: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	27: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	26: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
	25: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	24: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
	23: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
	22: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>'
	21: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
	20: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
	19: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
	18: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument'
	17: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
	16: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	15: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	14: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load'
	13: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
	12: from /data/redmine/redmine-4.0.0/config/initializers/30-redmine.rb:21:in `<top (required)>'
	11: from /data/redmine/redmine-4.0.0/lib/redmine/plugin.rb:164:in `load'
	10: from /data/redmine/redmine-4.0.0/lib/redmine/plugin.rb:164:in `each'
	 9: from /data/redmine/redmine-4.0.0/lib/redmine/plugin.rb:173:in `block in load'
	 8: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 7: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 6: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
	 5: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 4: from /data/redmine/redmine-4.0.0/plugins/redmine_time_log_pdf_export/init.rb:2:in `<top (required)>'
	 3: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
	 2: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
	 1: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- LogTimeHelper (LoadError)

**Comment by rnitc** [comment]
> Regarding the log did you have the right permission to log folder?
yes I have and i can see the other logs 

>Assuming you run Redmine with a user named "redmine":
yes its redmine

>sudo chown -R redmine:redmine files log tmp public/plugin_assets
>sudo chmod -R 755 files log tmp public/plugin_assets
>You have to run these cmd.
yes i executed these command succesfully and still it did not work. also would like to tell you that have other plugins which  iam  using and its working properly.

I tried again reinstallation no luck..

**Comment by ahamdan1990** [comment]
> > bundle exec rails server webrick -e production
> 
> here is the log file after executing the above command
> 
> redmine@vps:~/redmine-4.0.0$ bundle exec rails server webrick -e production
> => Booting WEBrick
> => Rails 5.2.2 application starting in production on http://0.0.0.0:3000
> => Run `rails server -h` for more startup options
> Exiting
> Traceback (most recent call last):
> 72: from bin/rails:4:in `<main>' 71: from bin/rails:4:in `require'
> 70: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands.rb:18:in `<top (required)>' 69: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
> 68: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform' 67: from /usr/share/rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
> 66: from /usr/share/rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command' 65: from /usr/share/rvm/gems/ruby-2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
> 64: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `perform' 63: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:142:in `tap'
> 62: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:147:in `block in perform' 61: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:53:in `start'
> 60: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:283:in `start' 59: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:354:in `wrapped_app'
> 58: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/commands/server/server_command.rb:27:in `app' 57: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:219:in `app'
> 56: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/server.rb:319:in `build_app_and_options_from_config' 55: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
> 54: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string' 53: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
> 52: from config.ru:in `<main>' 51: from config.ru:in `new'
> 50: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize' 49: from /usr/share/rvm/gems/ruby-2.5.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
> 48: from config.ru:3:in `block in <main>' 47: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
> 46: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency' 45: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
> 44: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require' 43: from /data/redmine/redmine-4.0.0/config/environment.rb:14:in `<top (required)>'
> 42: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!' 41: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
> 40: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each' 39: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
> 38: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component' 37: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `call'
> 36: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:347:in `each' 35: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
> 34: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from' 33: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:415:in `call'
> 32: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `tsort_each_child' 31: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:50:in `each'
> 30: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from' 29: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
> 28: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from' 27: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
> 26: from /usr/share/rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each' 25: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
> 24: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run' 23: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
> 22: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `block in <class:Engine>' 21: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:613:in `each'
> 20: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>' 19: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:656:in `load_config_initializer'
> 18: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/notifications.rb:170:in `instrument' 17: from /usr/share/rvm/gems/ruby-2.5.0/gems/railties-5.2.2/lib/rails/engine.rb:657:in `block in load_config_initializer'
> 16: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load' 15: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
> 14: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `block in load' 13: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:285:in `load'
> 12: from /data/redmine/redmine-4.0.0/config/initializers/30-redmine.rb:21:in `<top (required)>' 11: from /data/redmine/redmine-4.0.0/lib/redmine/plugin.rb:164:in `load'
> 10: from /data/redmine/redmine-4.0.0/lib/redmine/plugin.rb:164:in `each' 9: from /data/redmine/redmine-4.0.0/lib/redmine/plugin.rb:173:in `block in load'
> 8: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require' 7: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
> 6: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require' 5: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
> 4: from /data/redmine/redmine-4.0.0/plugins/redmine_time_log_pdf_export/init.rb:2:in `<top (required)>' 3: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
> 2: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency' 1: from /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
> /usr/share/rvm/gems/ruby-2.5.0/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- LogTimeHelper (LoadError)

Oh it's not loading the logtimehelper from plugin lib i renamed them in init.rb without capital letters.
Can you please try it again and let me know if it will works

**Comment by rnitc** [comment]
Hey Thanks, it worked.
